---
title: "EPR3 varnames"
author: "`r Sys.Date()`"
knit: (function(input_file, encoding, ...) {rmarkdown::render(input_file, encoding=encoding, output_dir=getwd())}) # wut
output:
  pdf_document:
    keep_tex: yes
    toc: true
    toc_depth: 2
    includes:
      in_header: baser/base.tex
    fig_caption: true
geometry: margin=1in
subparagraph: true
params:
  from_scratch: true
  # from_scratch: false
linkcolor: blue
fontfamily: fourier
bibliography: baser/arsenoff.bib
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::rmarkdown}
editor_options: 
  chunk_output_type: inline
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(eval=FALSE, include=FALSE)
```

\ztab
\blandscape
\begin{center}
\begin{tabular}{rdddddddddddd}
  \multicolumn{1}{c}{ } & \multicolumn{2}{c}{A} & \multicolumn{2}{c}{B} & \multicolumn{2}{c}{C} & \multicolumn{2}{c}{D} & \multicolumn{2}{c}{E} & \multicolumn{2}{c}{F}  \\  \cmidrule(l){2-3} \cmidrule(l){4-5} \cmidrule(l){6-7} \cmidrule(l){8-9} \cmidrule(l){10-11} \cmidrule(l){12-13}\multicolumn{1}{c}{ } & \multicolumn{1}{c}{} & \multicolumn{1}{c}{FEs} & \multicolumn{1}{c}{} & \multicolumn{1}{c}{FEs} & \multicolumn{1}{c}{} & \multicolumn{1}{c}{FEs} & \multicolumn{1}{c}{} & \multicolumn{1}{c}{FEs} & \multicolumn{1}{c}{} & \multicolumn{1}{c}{FEs} & \multicolumn{1}{c}{} & \multicolumn{1}{c}{FEs} \\ 
  \hline
\rule{0pt}{2.25ex}minority &  &  & -0.032^{*} & 0.014^{} & -0.046^{**} & 0.006^{} &  &  & -0.084^{**} & -0.034^{} & -0.104^{***} & -0.045^{} \\ 
   &  &  & (0.014) & (0.020) & (0.015) & (0.021) &  &  & (0.031) & (0.036) & (0.028) & (0.032) \\ 
  \rule{0pt}{2.25ex}Dissim. & 0.054^{***} & 0.014^{} &  &  & 0.059^{***} & 0.013^{} & 0.045^{**} & 0.011^{} &  &  & 0.055^{***} & 0.018^{} \\ 
   & (0.012) & (0.014) &  &  & (0.012) & (0.015) & (0.014) & (0.016) &  &  & (0.014) & (0.015) \\ 
  \rule{0pt}{2.25ex}poverty &  &  &  &  &  &  & 0.078^{} & 0.091^{} & 0.183^{*} & 0.125^{} & 0.176^{*} & 0.127^{} \\ 
   &  &  &  &  &  &  & (0.049) & (0.063) & (0.080) & (0.087) & (0.075) & (0.085) \\ 
  \rule{0pt}{2.25ex}Mfg. &  &  &  &  &  &  & 0.062^{} & -0.065^{} & 0.055^{} & -0.062^{} & -0.011^{} & -0.075^{} \\ 
   &  &  &  &  &  &  & (0.040) & (0.060) & (0.050) & (0.064) & (0.047) & (0.062) \\ 
  \rule{0pt}{2.25ex}rural &  &  &  &  &  &  & 0.011^{} & 0.009^{} & 0.005^{} & 0.008^{} & 0.006^{} & 0.009^{} \\ 
   &  &  &  &  &  &  & (0.008) & (0.009) & (0.010) & (0.009) & (0.009) & (0.009) \\ 
   \hline
\rule{0pt}{2.25ex}AIC & \multicolumn{1}{c}{-1512.893} & \multicolumn{1}{c}{-1565.266} & \multicolumn{1}{c}{-1497.461} & \multicolumn{1}{c}{-1564.445} & \multicolumn{1}{c}{-1518.449} & \multicolumn{1}{c}{-1563.33} & \multicolumn{1}{c}{-1515.197} & \multicolumn{1}{c}{-1569.029} & \multicolumn{1}{c}{-1515.61} & \multicolumn{1}{c}{-1569.747} & \multicolumn{1}{c}{-1531.952} & \multicolumn{1}{c}{-1569.523} \\ 
  n & \multicolumn{1}{c}{348} & \multicolumn{1}{c}{348} & \multicolumn{1}{c}{348} & \multicolumn{1}{c}{348} & \multicolumn{1}{c}{348} & \multicolumn{1}{c}{348} & \multicolumn{1}{c}{348} & \multicolumn{1}{c}{348} & \multicolumn{1}{c}{348} & \multicolumn{1}{c}{348} & \multicolumn{1}{c}{348} & \multicolumn{1}{c}{348} \\ 
   \hline \multicolumn{13}{r}{+ p < 0.1; * p < 0.05; ** p < 0.01; *** p < 0.001; standard errors in parentheses} \\\end{tabular}
\captionof{table}{}
\end{center}
\elandscape